export const dashboard = <i className="fa-solid fa-chart-line"></i>
export const transactions = <i className="fa fa-credit-card"></i>
export const categories = <i className="fa fa-tags"></i>
export const accounts = <i className="fa fa-wallet"></i>
export const settings = <i className="fa fa-cog"></i>
export const logout = <i className="fa-solid fa-right-from-bracket"></i>
export const trend = <i className="fa-solid fa-money-check"></i>
export const expenses = <i className="fa-solid fa-money-bill-1"></i>
export const money = <i className="fa fa-money-bill"></i>
export const freelance = <i className ="fa fa-earth-americas"></i>
export const stocks = <i className="fa fa-arrow-trend-up"></i>
export const bitcoin = <i className="fa fa-bitcoin"></i>
export const piggy = <i className="fa fa-piggy-bank"></i>
export const yt = <i className="fa fa-youtube"></i>
export const card = <i className="fa fa-cc-visa"></i>
export const users = <i className="fa fa-users-between-lines"></i>
export const dollar = <i className="fa fa-dollar-sign"></i>
export const calender = <i className="fa fa-calendar"></i>
export const comment = <i className="fa fa-comment"></i>
export const plus = <i className="fa fa-plus"></i>
export const trash = <i className="fa fa-trash"></i>
export const signout = <i className="fa fa-right-from-bracket"></i>
export const takeaway = <i className="fa fa-utensils"></i>
export const clothing = <i className="fa fa-shirt"></i>
export const book = <i className="fa fa-book-open"></i>
export const food = <i className="fa fa-bowl-food"></i>
export const medical = <i className="fa fa-briefcase-medical"></i>
export const tv = <i className="fa fa-tv"></i>
export const circle = <i className="fa fa-circle-dot"></i>
export const rupee = <i class="fa fa-inr"></i>